"""
Harmonic Rings — Polynomial-ring analog for pitch classes.

Analogous to Oscar.jl's Rings module (polynomial rings, integer rings).

The fundamental structure is Z/nZ where n is the number of pitch classes
(default 12 for chromatic equal temperament). Addition = transposition,
multiplication = interval composition.

The ideal structure of Z/12Z yields musically meaningful objects:
  {0}              — unison
  {0, 6}           — tritone pair
  {0, 4, 8}        — augmented triad
  {0, 3, 6, 9}     — diminished seventh chord
  {0, 2, 4, 6, 8, 10} — whole-tone scale
  Z/12Z            — chromatic scale

These are ALL ideals of Z/12Z (since Z/nZ is a principal ideal ring,
ideals correspond to divisors of n).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from fractions import Fraction
from math import gcd
from functools import reduce
from typing import FrozenSet, Iterable, List, Optional, Set, Tuple


class HarmonicRing:
    """Ring of pitch classes modulo n (default 12).

    The ring Z/nZ where addition is transposition and multiplication is
    interval composition. This is the fundamental algebraic structure for
    equal-division pitch-class set theory.

    Parameters
    ----------
    modulus : int
        Number of pitch divisions per octave (default 12).

    Examples
    --------
    >>> hr = HarmonicRing(12)
    >>> hr.add(7, 5)       # G + E = C (mod 12)
    0
    >>> hr.multiply(3, 4)  # M3 × M3 wraps
    0
    """

    def __init__(self, modulus: int = 12) -> None:
        if modulus < 1:
            raise ValueError(f"modulus must be ≥ 1, got {modulus}")
        self._modulus = modulus

    @property
    def modulus(self) -> int:
        """Number of pitch divisions per octave."""
        return self._modulus

    @property
    def zero(self) -> int:
        """Additive identity (unison)."""
        return 0

    @property
    def one(self) -> int:
        """Multiplicative identity (unison interval)."""
        return 1

    def add(self, a: int, b: int) -> int:
        """Transposition: (a + b) mod n.

        Parameters
        ----------
        a, b : int
            Pitch classes.

        Returns
        -------
        int
            Sum modulo n.
        """
        return (a + b) % self._modulus

    def subtract(self, a: int, b: int) -> int:
        """Inverse transposition: (a - b) mod n."""
        return (a - b) % self._modulus

    def multiply(self, a: int, b: int) -> int:
        """Interval composition: (a × b) mod n.

        Multiplication in Z/nZ corresponds to composing intervals.
        For example, multiplying by 7 (a fifth) transposes by a fifth.
        """
        return (a * b) % self._modulus

    def negate(self, a: int) -> int:
        """Additive inverse (inversion): -a mod n."""
        return (-a) % self._modulus

    def invert(self, a: int, n: int = 0) -> int:
        """Interval inversion around n: (n - a) mod modulus.

        Parameters
        ----------
        a : int
            Pitch class to invert.
        n : int
            Axis of inversion (default 0 = C).

        Returns
        -------
        int
            Inverted pitch class.
        """
        return (n - a) % self._modulus

    def transpose(self, pc: int, interval: int) -> int:
        """Transpose pitch class by interval.

        Parameters
        ----------
        pc : int
            Pitch class.
        interval : int
            Interval in semitones.

        Returns
        -------
        int
            Transposed pitch class.
        """
        return (pc + interval) % self._modulus

    def elements(self) -> range:
        """Return all pitch classes {0, 1, ..., n-1}."""
        return range(self._modulus)

    def units(self) -> List[int]:
        """Return multiplicative units of Z/nZ.

        These are the elements coprime to n, forming the group (Z/nZ)×.
        In Z/12Z: {1, 5, 7, 11} — the "M-operation" transformations.
        """
        return [k for k in range(1, self._modulus) if gcd(k, self._modulus) == 1]

    def all_ideals(self) -> List[Set[int]]:
        """Return all ideals of Z/nZ.

        Ideals of Z/nZ correspond to divisors d of n: the ideal is the
        subgroup generated by d, which is {0, d, 2d, ..., n-d}.

        For n=12, divisors are 1,2,3,4,6,12 yielding ideals of sizes
        12, 6, 4, 3, 2, 1 respectively.

        Returns
        -------
        list of set
            All ideals, sorted by size (smallest first).
        """
        ideals: List[Set[int]] = []
        for d in range(1, self._modulus + 1):
            if self._modulus % d == 0:
                ideals.append(set(range(0, self._modulus, d)))
        return sorted(ideals, key=len)

    def ideal_generated_by(self, *generators: int) -> ChordIdeal:
        """Compute the ideal generated by the given pitch classes.

        Parameters
        ----------
        *generators : int
            Pitch classes generating the ideal.

        Returns
        -------
        ChordIdeal
        """
        gen_set = set(g % self._modulus for g in generators)
        # Ideal in Z/nZ generated by {g1, ..., gk} is the subgroup
        # generated by gcd(g1, ..., gk, n)
        all_gens = list(gen_set) + [self._modulus]
        g = reduce(gcd, all_gens)
        elements = frozenset(range(0, self._modulus, g))
        return ChordIdeal(ring=self, generators=frozenset(gen_set), elements=elements)

    def chord_ideal(self, chord: Iterable[int]) -> ChordIdeal:
        """Compute the ideal generated by a chord's pitch classes.

        Parameters
        ----------
        chord : iterable of int
            Pitch classes forming the chord.

        Returns
        -------
        ChordIdeal
        """
        return self.ideal_generated_by(*chord)

    def interval_class(self, a: int, b: int) -> int:
        """Interval class between two pitch classes.

        The interval class is min(|a-b|, n - |a-b|), always in [0, n//2].

        Parameters
        ----------
        a, b : int
            Pitch classes.

        Returns
        -------
        int
            Interval class.
        """
        diff = abs(a - b) % self._modulus
        return min(diff, self._modulus - diff)

    def pitch_class_set(self, notes: Iterable[int]) -> FrozenSet[int]:
        """Reduce a collection of notes to a pitch-class set.

        Parameters
        ----------
        notes : iterable of int
            MIDI note numbers or pitch classes.

        Returns
        -------
        frozenset of int
            Pitch classes modulo n.
        """
        return frozenset(n % self._modulus for n in notes)

    def prime_form(self, notes: Iterable[int]) -> Tuple[int, ...]:
        """Compute the prime form of a pitch-class set.

        The prime form is the most left-packed rotation of the normal order,
        compared with its inversion. Standard Fortean prime form.

        Parameters
        ----------
        notes : iterable of int
            Pitch classes.

        Returns
        -------
        tuple of int
            Prime form as sorted intervals from 0.
        """
        pcs = sorted(set(n % self._modulus for n in notes))
        if not pcs:
            return ()

        n = len(pcs)

        # Generate all rotations
        def rotations(seq):
            return [tuple(seq[i:] + seq[:i]) for i in range(len(seq))]

        # Normal order: most left-packed rotation
        def normal_order(pitch_classes):
            if len(pitch_classes) <= 1:
                return tuple(pitch_classes)
            rots = rotations(pitch_classes)
            # Sort by: smallest last-first interval, then most left-packed
            def sort_key(rot):
                intervals = tuple(rot[i+1] - rot[i] for i in range(len(rot)-1))
                span = (rot[-1] - rot[0]) % self._modulus
                return (span, intervals)
            return min(rots, key=sort_key)

        # Transpose to start at 0
        def transpose_to_zero(seq):
            t = seq[0]
            return tuple((x - t) % self._modulus for x in seq)

        # Get normal order
        norm = normal_order(pcs)
        prime = transpose_to_zero(norm)

        # Compare with inverted form
        inverted = sorted(set(self._modulus - p for p in prime))
        inv_norm = normal_order(inverted)
        inv_prime = transpose_to_zero(inv_norm)

        # Return the more left-packed one
        def packness(seq):
            return tuple(seq[i+1] - seq[i] for i in range(len(seq)-1))

        if packness(prime) <= packness(inv_prime):
            return prime
        return inv_prime

    def __repr__(self) -> str:
        return f"HarmonicRing(modulus={self._modulus})"

    def __eq__(self, other: object) -> bool:
        return isinstance(other, HarmonicRing) and self._modulus == other._modulus

    def __hash__(self) -> int:
        return hash(("HarmonicRing", self._modulus))


class IntervalRing:
    """Ring of musical intervals with just-intonation ratios.

    Represents intervals as positive rational numbers (frequency ratios).
    Multiplication of ratios corresponds to addition of intervals.
    The identity is 1/1 (unison). Only ratios with prime factors in
    the given limit are included.

    Parameters
    ----------
    prime_limit : tuple of int
        Allowed prime factors (default (2, 3, 5, 7, 11) — the 11-limit).

    Examples
    --------
    >>> ir = IntervalRing()
    >>> ir.add(Fraction(3, 2), Fraction(5, 4))  # P5 + M3 = M7
    Fraction(15, 8)
    """

    def __init__(self, prime_limit: Tuple[int, ...] = (2, 3, 5, 7, 11)) -> None:
        self._prime_limit = tuple(sorted(prime_limit))

    @property
    def prime_limit(self) -> Tuple[int, ...]:
        """Allowed prime factors."""
        return self._prime_limit

    @property
    def zero(self) -> Fraction:
        """Multiplicative identity for frequency ratios (unison = 1/1)."""
        return Fraction(1, 1)

    @property
    def one(self) -> Fraction:
        """Same as zero — the identity element."""
        return Fraction(1, 1)

    def add(self, a: Fraction, b: Fraction) -> Fraction:
        """Add intervals (multiply frequency ratios).

        In just intonation, adding intervals means multiplying their
        frequency ratios: (3/2) + (5/4) = (3/2) × (5/4) = 15/8.

        Parameters
        ----------
        a, b : Fraction
            Frequency ratios.

        Returns
        -------
        Fraction
            Product ratio.
        """
        result = a * b
        self._check_prime_limit(result)
        return result

    def subtract(self, a: Fraction, b: Fraction) -> Fraction:
        """Subtract intervals (divide frequency ratios).

        Parameters
        ----------
        a, b : Fraction
            Frequency ratios.

        Returns
        -------
        Fraction
            Quotient ratio.
        """
        result = a / b
        self._check_prime_limit(result)
        return result

    def multiply(self, a: Fraction, n: int) -> Fraction:
        """Stack an interval n times: ratio^n.

        Parameters
        ----------
        a : Fraction
            Frequency ratio.
        n : int
            Number of times to stack.

        Returns
        -------
        Fraction
        """
        result = a ** n
        self._check_prime_limit(result)
        return result

    def invert(self, a: Fraction) -> Fraction:
        """Invert an interval: 1/a."""
        return Fraction(1, 1) / a

    def cents(self, ratio: Fraction) -> float:
        """Convert a frequency ratio to cents.

        Parameters
        ----------
        ratio : Fraction
            Frequency ratio.

        Returns
        -------
        float
            Size in cents (1200 × log₂(ratio)).
        """
        import math
        return 1200.0 * math.log2(float(ratio))

    def ratio_from_cents(self, cents: float) -> Fraction:
        """Approximate a cent value as a just-intonation ratio.

        Parameters
        ----------
        cents : float
            Size in cents.

        Returns
        -------
        Fraction
            Best approximation within the prime limit.
        """
        import math
        return Fraction(2) ** Fraction(cents / 1200.0).limit_denominator(10000)

    def _check_prime_limit(self, ratio: Fraction) -> None:
        """Verify ratio only uses allowed prime factors."""
        for p in self._prime_factors(ratio.numerator):
            if p not in self._prime_limit:
                raise ValueError(
                    f"Prime {p} in numerator exceeds limit {self._prime_limit}"
                )
        for p in self._prime_factors(ratio.denominator):
            if p not in self._prime_limit:
                raise ValueError(
                    f"Prime {p} in denominator exceeds limit {self._prime_limit}"
                )

    @staticmethod
    def _prime_factors(n: int) -> Set[int]:
        """Return prime factors of n."""
        factors: Set[int] = set()
        d = 2
        while d * d <= n:
            while n % d == 0:
                factors.add(d)
                n //= d
            d += 1
        if n > 1:
            factors.add(n)
        return factors

    def __repr__(self) -> str:
        return f"IntervalRing(prime_limit={self._prime_limit})"


@dataclass(frozen=True)
class ChordIdeal:
    """An ideal in the HarmonicRing generated by chord tones.

    In Z/nZ, every ideal is principal (generated by gcd of generators and n).
    The quotient ring Z/nZ / I measures how much tonal information is lost
    when collapsing to the ideal's equivalence classes.

    Parameters
    ----------
    ring : HarmonicRing
        Parent ring.
    generators : frozenset of int
        Pitch classes generating the ideal.
    elements : frozenset of int
        All elements of the ideal.

    Examples
    --------
    >>> hr = HarmonicRing(12)
    >>> ci = hr.chord_ideal([0, 4, 7])  # C major
    >>> ci.generators
    frozenset({0, 4, 7})
    """

    ring: HarmonicRing
    generators: FrozenSet[int]
    elements: FrozenSet[int]

    def contains(self, pc: int) -> bool:
        """Check if a pitch class belongs to this ideal.

        Parameters
        ----------
        pc : int
            Pitch class.

        Returns
        -------
        bool
        """
        return pc % self.ring.modulus in self.elements

    def cosets(self) -> List[FrozenSet[int]]:
        """Compute the quotient ring Z/nZ / I as cosets.

        Returns
        -------
        list of frozenset
            Cosets of this ideal in the parent ring.
        """
        n = self.ring.modulus
        if not self.elements:
            return [frozenset(range(n))]
        # Find generator of ideal (smallest positive element)
        gen = min(e for e in self.elements if e > 0) if any(e > 0 for e in self.elements) else n
        coset_size = len(self.elements)
        cosets = []
        for i in range(0, n, gen):
            coset = frozenset((i + e) % n for e in self.elements)
            if coset not in cosets:
                cosets.append(coset)
        return cosets

    def quotient_size(self) -> int:
        """Size of the quotient ring Z/nZ / I.

        Returns
        -------
        int
            Number of cosets.
        """
        return len(self.cosets())

    def is_trivial(self) -> bool:
        """Whether this is the zero ideal {0}."""
        return self.elements == frozenset({0})

    def is_full(self) -> bool:
        """Whether this is the full ring Z/nZ."""
        return self.elements == frozenset(range(self.ring.modulus))

    def index(self) -> int:
        """Index [Z/nZ : I] = |Z/nZ| / |I|."""
        return self.ring.modulus // len(self.elements)

    def __contains__(self, pc: int) -> bool:
        return self.contains(pc)

    def __repr__(self) -> str:
        gens = sorted(self.generators)
        return f"ChordIdeal(generators={gens}, elements={sorted(self.elements)})"
